server:
  port: 8082

spring:
  application:
    name: employee

  profiles:
    active: ${ACTIVE_PROFILE:local}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4992663gulnaree

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        envers:
          audit_table_suffix: _AUD
          revision_field_name: REV
          revision_type_field_name: REVTYPE
          store_data_at_delete: true

device:
  service:
    url: http://localhost:8081